language: python

python:
  - "3.6"

services:
  - mysql

before_install:
  - mysql -u root --password="rafed" < database/testdb.sql

install:
  - pip install -r webapi/requirements.txt
  - cd webapi && pip install -e .

before_script:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('rafed') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root

script:
  - python3 -m pytest --cov=./

after_success:
  - codecov -t 0ec0d1a7-1932-43e4-a2fd-67c633c69ef5
